[package]
changelog = "CHANGELOG.md"
versioned_files = ["Cargo.toml"]

[[workflows]]
name = "document-change"


[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"
ignore_conventional_commits = true

[[workflows.steps]]
type = "Command"
shell = true
command = "cargo c && git add -A"

# Commit the changes that PrepareRelease added
[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: Bump to version\""
variables = {"version" = "Version"}

# Push the commit and the new tag to our remote repository.
[[workflows.steps]]
type = "Command"
command = "git push"


# Create a GitHub release for each package.
[[workflows.steps]]
type = "Release"

[[workflows.steps]]
type = "Command"
command = "git push --tags"
