# Jobs run on pull request
name: CI main
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1
        with:
          components: rustfmt
          bins: taplo-cli
          cache-base: main
      - name: Run format
        run: |
          cargo fmt --all --check
          taplo format --check

  lint:
    name: Lint Rust Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1
        with:
          components: clippy
          cache-base: main
      - name: Run clippy
        run: cargo clippy --all-targets -- --deny warnings