# Jobs run on pull request
name: Pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
          components: rustfmt
          bins: taplo-cli
          cache-base: main
      - name: Run format
        run: |
          cargo fmt --all --check
          taplo format --check

  lint:
    name: Lint Rust Files
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
          components: clippy
          cache-base: main
      - name: Run clippy
        run: cargo clippy --all-targets -- --deny warnings