# Jobs run on pull request
name: Pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install toolchain
        uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f # v1
        with:
          components: rustfmt
          bins: taplo-cli
          cache-base: main
      - name: Run format
        run: |
          cargo fmt --all --check
          taplo format --check

  lint:
    name: Lint Rust Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install toolchain
        uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f # v1
        with:
          components: clippy
          cache-base: main
      - name: Run clippy
        run: cargo clippy --all-targets -- --deny warnings